[window]
dimensions = { columns = 120, lines = 40 }

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
size = 14

[colors]
[colors.primary]
background = "#303030"

[env]
TERM = "alacritty"
